<?php

use Illuminate\Database\Seeder;

class LabTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tests = [

            "Sugar Fasting",
            "2hrs, ABF",
            "After 75gm,Glucose",
            "Random",
            "MP",
            "BT,CT",
            "R/E Stool",
            "HCT/PCV",
            "CBT Stool",
            "Pregnancy Test",
            "R/E Urine",
            "TC,DC,Hb%,ESR",
            "CE Count",
            "Platelet Count",
            "Blood Film",
            "Reticulocyte Count",
            "S. Cholesterol",
            "Vaginal Swab R/E",
            "GM Stain",
            "HBs AG (Screening)",
            "GTT",
            "Urea/BUN",
            "SGOT",
            "SGPT",
            "Alk. Phosphatase",
            "Sputum R/E",
            "CBC,ESR",
            "Prothombin Time",
            "S. Bilirubin (Total/Direct,Indirect)",
            "Widal Test",
            "S. Total Portion",
            "TSH",
            "APTT",
            "C/S Urine",
            "CRP",
            "C/S Stool",
            "HBs AG (Elisa/Confirmatory)",
            "Spot Urine Protein Creatinine Ratio",
            "T3",
            "T4",
            "S. Electrolytes",
            "Anti HBs",
            "Hbe Ag",
            "Anti HCV",
            "Anti HAV-IgM",
            "Anti HBc-IgM",
            "Anti HEV-IgM",
            "Anti HBc-IgM",
            "Hb A1c",
            "Estradiol",
            "Progesterone",
            "Testosterone",
            "LH",
            "FSH",
            "PTH",
            "ACTH",
            "FNAC",
            "Pap's Smear",
            "GFR",
            "CK-MB",
            "IgM.S",
            "IgG.S",
            "ANA",
            "Blood for C/S",
            "C3",
            "C4",
            "IgE.S",
            "IgA.S",
            "CA15.3",
            "Ca-19.9",
            "AFP",
            "CEA",
            "BHCG",
            "PSA",
            "CPK",
            "S. Iron",
            "Ferritin",
            "Folic Acid",
            "Folate",
            "Urine for micro albumin",
            "FT3",
            "FT4",
            "Prolactin",
            "Dengue ICT",
            "CMV IgG",
            "Lipid Profile",
            "FDP",
            "ICT Malaria",
            "Hb Electrophoresis",
            "Protein Electrophoresis",
            "Anti DNA",
            "ALLERGY PANEL",
            "HBV DNA(Quantitative)",
            "Thyroid Scan",
            "131 Uptake & Scan or Both",
            "DTPA Renogram with GFR",
            "DTPA Renogram with Split Function Captopril Renogram",
            "Whole body Bone Scan",
            "Brain Perfusion Study {CBF/SPECT) Yesica Uretenic Reflux",
            "HIDA Scan",
            "Lung Perfusion Study",
            "G,I Bleeding Study",
            "Parotid Gland",
            "Lymphoscinfigraphy",
            "Breast Scintimammogrphy",
            "Liver Scan",
            "Testis Scan",
            "Renal Transplant study/evaluation DNSA renal scan",
            "3- Phase Bony Scan",
            "Liver -Spleen imaging/scan Hepatobiliary(HIDA) Scan",
            "Meckel's diverticulum's Scanning Salivary gland imaging",
            "SPECT Cardiac Perfusion Scan iT1201/Myoview/MIBI)",
            "Cardiac Infarct Scanning",
            "Iodine -131 Whole Body Scanning Parathyroid Scanning",
            "Testicular Flow Study",
            "HCV-RNA (Quantitative)",
            "HLA-B 27 (DNA)",
            "HCV- Genotyping",
            "CMV-DNA (Qualitative)",
            "MTB-PCR (Qualitative)",
            "HPV-DNA",
            "T-Cell/B-Cell Crossmatch",
            "B-Cell only Crossmatch",
            "T-Cell Only Crossmatch",
            "Barr Body Test",
            "Karyolyping of Human Chromosome Tissue Typing",
            "HLA-A",
            "HLA-B",
            "HLA-DR",
            "HLA~C",
            "HLA-DQ",
            "Lumber Spine A/P (BONE DENSITOMETRY)",
            "Left/Right Femur (BONE DENSITOMETRY)",
            "Both Femur (BONE DENSITOMETRY)",
            "Total Body (BONE DENSITOMETRY)",
            "Whole Abdomen (4D ULTRASONOGRAPHY)",
            "Upper Abdomen (4D ULTRASONOGRAPHY)",
            "Lower Abdomen (4D ULTRASONOGRAPHY)",
            "HBS/Liver/GB (4D ULTRASONOGRAPHY)",
            "Uterus & Adnexae (4D ULTRASONOGRAPHY)",
            "Pelvic Organs (4D ULTRASONOGRAPHY)",
            "Pregnancy Profile (4D ULTRASONOGRAPHY)",
            "Thyroid Gland (4D ULTRASONOGRAPHY)",
            "Pardid Gland (4D ULTRASONOGRAPHY)",
            "Brain(4D ULTRASONOGRAPHY)",
            "Scrotum/Testies (4D ULTRASONOGRAPHY)",
            "Trans rectal (4D ULTRASONOGRAPHY)",
            "Trans Vaginal (4D ULTRASONOGRAPHY)",
            "Breast (4D ULTRASONOGRAPHY)",
            "Daplux/Vascular USG (4D ULTRASONOGRAPHY)",
            "Color Doppler USG (4D ULTRASONOGRAPHY)",
            "KUB (4D ULTRASONOGRAPHY)",
            "Chest: P/A, A/P, Apical, Oblique Lateral, Penetrating ( Plain X-RAY)",
            "Skull: NP, Oblique, Lateral  ( Plain X-RAY)",
            "Shoulder Joint [L/R): A/P, Swimmers view  ( Plain X-RAY)",
            "Elbow Joint (UR): A/P, Oblique, and Lateral  ( Plain X-RAY)",
            "Wrist Joint [L/R): A/P, Oblique, and Lateral  ( Plain X-RAY)",
            "Scaphoid view  ( Plain X-RAY)",
            "Hip Joint (L/R): A/P, Oblique, Lateral  ( Plain X-RAY)",
            "Knee Joint (L/R): A/P, Oblique, Lateral  ( Plain X-RAY)",
            "Ankle Joint (L/R): A/P, Oblique, Lateral  ( Plain X-RAY)",
            "PNS: OM, Lateral view  ( Plain X-RAY)",
            "Nasopharyx (True Lateral View)  ( Plain X-RAY)",
            "Pelvis: A/P, Frogleg view  ( Plain X-RAY)",
            "Cervical Spine: A/P, Lateral, Oblique  ( Plain X-RAY)",
            "Dorsal Spine: A/P, Lateral, Oblique  ( Plain X-RAY)",
            "L/S Spine: A/P, Lateral, Oblique  ( Plain X-RAY)",
            "Coccyx Joints: A/P, Lateral  ( Plain X-RAY)",
            "S. L Joint: Oblique (Both)  ( Plain X-RAY)",
            "Soft Tissue Neck: A/P, Lateral  ( Plain X-RAY)",
            "Abdomen (Erect/Supine)  ( Plain X-RAY)",
            "Tooth (Occusal view)  ( Plain X-RAY)",
            "Nasal Bone (Lateral view) ( Plain X-RAY)",
            "Mandible (Oblique view)  ( Plain X-RAY)",
            "TM Joint (Open and Close Mouth)  ( Plain X-RAY)",
            "Mastoid (Towns, Strenvers view)  ( Plain X-RAY)",
            "Optic Foramen view  ( Plain X-RAY)",
            "Orbit: A/P view  ( Plain X-RAY)",
            "KUB  ( Plain X-RAY)",
            "OPG  ( Plain X-RAY)",
            "Sialogram (Contrast X-RAY)",
            "Sinogram (Contrast X-RAY)",
            "O.C.G. (Contrast X-RAY)",
            "IVU/IVP (Contrast X-RAY)",
            "MCU (Contrast X-RAY)",
            "Retro Urethrogram / Cystogram (Contrast X-RAY)",
            "Ba-Meal, S/D (Contrast X-RAY)",
            "Ba-Follow Through (Contrast X-RAY)",
            "Ba-Swallow/oesophagus (Contrast X-RAY)",
            "Ba-Enema Double Contrast (Contrast X-RAY)",
            "Hysterosalphingogram (HSG) (Contrast X-RAY)",
            "MYELOGRAPHY (Contrast X-RAY)",
            "Lumber (Contrast X-RAY)",
            "Lumbo-Dorsal (Contrast X-RAY)",
            "Cervical (Contrast X-RAY)",
            "Total/Full (Contrast X-RAY)",
            "Right Breast Mammography",
            "Left Breast Mammography",
            "Both Breast Mammography",
            "Endoscopy",
            "Colonoscopy",
            "Broncoscopy",
            "ERCP",
            "Lung Biopsy",
            "EMG",
            "NCV",
            "EEG",
            "Avoked Potential Test",
            "Automated Blood Culture",
            "Throat swab: *C/S; *Gram stain, *KLB stain",
            "Sputum: *C/S; *Gram stain; *AFB stain",
            "Urethral discharge: C/S; *Gram stain",
            "Prostatic smear: *C/S; *Gram stain",
            "HVS: *C/S; *Gram stain",
            "Cervical swab: *C/S; *Gram stain",
            "Wound swab: *C/S; *Gram stain",
            "Pus: *C/S; *Gram stain: *AFB stain",
            "Conjunctival [Rt/Lt): *C/S; *Gram stain",
            "Ear (Rt / Lt): *C/S, *Gram stain",
            "Umbilical swab: *C/S; *Gram stain",
            "Skin Scrapings: *M/E for Fungus",
            "Skin Scrapings: *Culture for Fungus",
            "Blood Grouping & Rh Factor",
            "Cross-matching",
            "Rh-Antibody Titre",
            "Coomb's Test ' Direct / Indirect",
            "VDRL [ Qualitative/Quantitative}",
            "TPHA ( Qualitative/Quantitative}",
            "Asa titre R,A / R, F test",
            "RoseWader test Mono Spot test",
            "Weil Felix test ( Anti Rickettsia Ab)",
            "Anti BruceIlo Ab Anti H. pylori IgG",
            "CFT for Filaria ICT for Filaria",
            "ICT for Kala Azar (Ag/Ab)",
            "Aldehyde Test",
            "ICT for Malaria (Ag/Ab}",
            "TORCH",
            "Anti Rubella IgG / IgM",
            "Anti-Cytomegalo !gG / IgM",
            "Anti-Herpes simplex (1 &2} IgG / IgM",
            "Anti Dengue IgM / IgG",
            "Anti HIV[ I & 2 )",
            "Total Protein    Calcium",
            "Phosphate    CCR",
            "VMA Uric   Acid",
            "Anti-TB IgA, IgG, IgM (ELISA)",
            "ICT for TB Antibody (Combined)",
            "Mantoux Test",
            "TUMOUR MARKERS",
            "Total PSA",
            "Free PSA",
            "CA-125",
            "Alpha-Feto Protein",
            "Cortisol",
            "Estradial / Estrogen",
            "Growth Hormone",
            "AUTOIMMUNITY",
            "ANF",
            "Anti-dsDNA",
            "Anti-Thyroid Ab",
            "C-ANCA",
            "P-ANCA",
            "Opiates",
            "Cannabinoids",
            "Digoxin",
            "Carbamazepine",
            "Benzodiazepine",
            "Lithium",
            "Vitamin B-12",
            "Ascorbic acid",
            "CPK",
            "CK-MB",
            "LDH",
            "Myoglobin",
            "Troponin T",
            "Troponin troponin-I",
            "proBNP",
            "Homocystine",
            "Prothrombin Time",
            "Plasma Fibrinogen",
            "Microscopic Examination",
            "Gram Stain",
            "AFB Stain",
            "C/S",
            "Biochemical: Protein / Sugar/Chloride",
            "Cytology / Malignant Cell I",
            "CT Guided FNA",
            "Cytology of other Fluids",
            "ECG",
            "ETT",
            "Halter Monitor",
            "Echo Cardiogram - 2D",
            "Echo Cardiogram Color Doppler",
            "TE Echo Cardiogram",
            "Cardiac Scan / Thallium Scan",
            "24 hrs computerized B.P monitor",
            "Angiogram (Coronary, Peripheral, Renal)",
            "PCV; MCV; MCH; MCHC",
            "Circulating Eosinophil Count",
            "Reticulocyte Count",
            "Malarial Parasite",
            "Microfilaria",
            "LE Cells",
            "L-D body (from bone marrow / blood / skin lesion)",
            "Bone Marrow Study",
            "Hb-Eletrophoresis",
            "Urine; R/M/E; Ketone Body; Bile Pigment/Salt Bence-Jone's Protein",
            "Urobilinogen",
            "Semen Analysis",
            "Blood Sugar: GTT / Fasting / Random / 2 Hrs AFB / 75 gm glucose",
            "Total Protein / A.G Ratio",
            "Gamma GT",
            "Lipid Profile: Cholesterol / HDL / LDL / Triglyceride",
            "Kidney profile:Micro-albumin",
            "Uric Acid",
            "S. Amylase",
            "S. Aldolase",
            "S, Acid Phosphatase (Total / Prostatic]",
            "Electrolytes: Na / K / Cl / TCO2",
            "Phosphate: Inorganic/Organic",
            "Iron Binding Capacity",
            "Spirometry with Reversibility",
            "Spirometry, Lung Volume & DLCO",
            "TLC (Body Box)",
            "Raw & Gaw",
            "Methacholine Challenge test",

        ];

        foreach ($tests as $test){
            \App\Models\LabTest::create(['name' => $test]);
        }

    }
}
